### ISSUE TITLE
packager option --asar fails with ENOENT

### ISSUE THREAD

**Issue by jnv** [electron/electron-compile#129]
I am running `electron-packager-runtime` with the following options:

```
electron-packager-compile . --version=1.3.5 --platform=linux --arch=x64 --out=./dist --overwrite --prune --asar
```

Now, with `--asar` option the command fails:

```
spawn node_modules/.bin/asar ENOENT
    at AnonymousObserver._onError (.../node_modules/spawn-rx/lib/index.js:345:18)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.error (.../node_modules/rx/dist/rx.js:1836:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (.../node_modules/rx/dist/rx.js:1772:14)
    at AnonymousObserver.tryCatcher (.../node_modules/rx/dist/rx.js:63:31)
    at AutoDetachObserverPrototype.error (.../node_modules/rx/dist/rx.js:5891:52)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onError .../node_modules/rx/dist/rx.js:1772:14)
    at ChildProcess.<anonymous> (.../node_modules/spawn-rx/lib/index.js:298:12)
    at emitOne (events.js:77:13)
    at ChildProcess.emit (events.js:169:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12) +15ms
```

It looks like `electron-packager-compile` is trying to execute `asar` from within the resources dir. Could it be some recent change on electron-packager's end?

Installed versions:

```
asar@0.12.3
electron-packager@8.0.0
electron-prebuilt-compile@1.3.5
```

**Comment by andymartinwork** [comment]
The electron-compile is using version 7.5.1 of the electron-packager. Perhaps the api changes breaks the packaging?

**Comment by jnv** [comment]
I am not sure why, but somehow the problem went away and Asar packaging now works, so I think I can close this issue.
I use electron-prebuilt-compile with electron-packager 8.3.0

**Comment by jnv** [comment]
It works for me now. Feel free to reopen the issue if you are running into the same problem.
