### ISSUE TITLE
Failed to compile index.html

### ISSUE THREAD

**Issue by abhinav2004** [electron/electron-compile#140]
Hi. I am trying to use electron-compile for my project but I have hit a bit of a snag. For some reason I am getting the following error:

```javascript
Failed to compile /Users/abhinavhardikar/Projects/Electron/PhoneManager/src/app.html: Cannot read property 'split' of null
TypeError: Cannot read property 'split' of null
    at rigHtmlDocumentToInitializeElectronCompile (/Users/abhinavhardikar/Projects/Electron/PhoneManager/node_modules/electron-compile/lib/protocol-hook.js:55:18)
    at Function._callee$ (/Users/abhinavhardikar/Projects/Electron/PhoneManager/node_modules/electron-compile/lib/protocol-hook.js:218:31)
    at tryCatch (/Users/abhinavhardikar/Projects/Electron/PhoneManager/node_modules/regenerator-runtime/runtime.js:62:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/abhinavhardikar/Projects/Electron/PhoneManager/node_modules/regenerator-runtime/runtime.js:336:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/abhinavhardikar/Projects/Electron/PhoneManager/node_modules/regenerator-runtime/runtime.js:95:21)
    at step (/Users/abhinavhardikar/Projects/Electron/PhoneManager/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Users/abhinavhardikar/Projects/Electron/PhoneManager/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:20
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

Following is the .compilrc

```
{
  "env": {
    "development": {
      "application/javascript": {
        "presets": ["es2016-node5", "react"],
        "sourceMaps": "inline"
      }
    },
    "production": {
      "application/javascript": {
        "presets": ["es2016-node5", "react"],
        "sourceMaps": "none"
      }
    }
  }
}
```

and following is the html it is trying to compile

```html
<html>
<head>
</head>
<body>
  <script src="app.js"></script>
</body>
</html>
```

Could someone guide me with this?

**Comment by abhinav2004** [comment]
Ok I found the problem. In the HTML I had to add 
```html
<!DOCTYPE html>
```
to the top of the html file.

**Comment by rdourado** [comment]
I'm having the same problem even with doctype.

**Comment by ddombrowsky** [comment]
same problem here with a simple HTML file.  Only this time I have the correct `DOCTYPE` at the top.  Perhaps I need some bypass checkers or something.

**Comment by ddombrowsky** [comment]
Answering myself:  not only is `DOCTYPE` required, the charset is required also:
```diff
--- content/test.html.orig      2018-02-20 05:56:55.836964634 -0500
+++ content/test.html   2018-02-20 05:56:04.528682903 -0500
@@ -1,6 +1,7 @@
 <!DOCTYPE html>
 <html>
 <head>
+<meta charset="utf-8">
 <title>Test</title>
 </head>
 <body>
```
