### ISSUE TITLE
Cannot find module './main' on windows

### ISSUE THREAD

**Issue by arekkas** [electron/electron-compile#165]
This works fine on OSX, but it doesn't work on windows.

**index.js**
```js
const path = require('path')
const appRoot = path.join(__dirname, '..');

require('electron-compile').init(appRoot, './main');
```

**output**
```
App threw an error during load
Error: Cannot find module './src/main'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (C:\workspace\js\creator\node_modules\electron\dist\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at Object.init (C:\workspace\js\creator\node_modules\electron-compile\lib\config-parser.js:279:16)
    at Object.<anonymous> (C:\workspace\js\creator\src\index.js:5:29)
    at Module._compile (module.js:556:32)
    at Object.require.extensions.(anonymous function) (C:\workspace\js\creator\node_modules\electron-compile\lib\require-hook.js:34:14)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
```

**folders**
![grafik](https://cloud.githubusercontent.com/assets/3372410/21615415/b4c0cb04-d1dd-11e6-9f84-f79f7727fa5b.png)

**Comment by paulcbetts** [comment]
I had issues with this as well :-/  Try:

```js
const path = require('path')
const appRoot = path.join(__dirname, '..');

require('electron-compile').init(appRoot, require.resolve('./main'));
```

**Comment by arekkas** [comment]
Yes, that solved it, thanks!
