### ISSUE TITLE
App randomly stopped working with Error: unexpected end of file

### ISSUE THREAD

**Issue by deepak** [electron/electron-compile#169]
App was working but now it does not start. error backtrace is 

```
electron-compile:sanitize-paths Cache miss for cachedRealpath: '/Users/deepak/Code/mine/electron-and-react/electron-webview-todo' => '/Users/deepak/Code/mine/electron-and-react/electron-webview-todo' +0ms
App threw an error during load
Error: unexpected end of file
    at Zlib._handle.onerror (zlib.js:370:17)
    at Gunzip.Zlib._processChunk (zlib.js:540:30)
    at zlibBufferSync (zlib.js:239:17)
    at Object.exports.gunzipSync (zlib.js:175:10)
    at createCompilerHostFromConfiguration (/Users/deepak/Code/mine/electron-and-react/electron-webview-todo/node_modules/electron-compile/lib/config-parser.js:298:42)
    at createCompilerHostFromBabelRcSync (/Users/deepak/Code/mine/electron-and-react/electron-webview-todo/node_modules/electron-compile/lib/config-parser.js:342:12)
    at createCompilerHostFromProjectRootSync (/Users/deepak/Code/mine/electron-and-react/electron-webview-todo/node_modules/electron-compile/lib/config-parser.js:391:10)
    at init (/Users/deepak/Code/mine/electron-and-react/electron-webview-todo/node_modules/electron-compile/lib/config-parser.js:274:22)
    at main (/Users/deepak/Code/mine/electron-and-react/electron-webview-todo/node_modules/electron-prebuilt-compile/lib/es6-init.js:38:29)
    at Object.<anonymous> (/Users/deepak/Code/mine/electron-and-react/electron-webview-todo/node_modules/electron-prebuilt-compile/lib/es6-init.js:41:1)
```

steps to reproduce:

1. clone https://github.com/deepak/react-todo and 
    - yarn/npm install
    - run app with `DEBUG=* PORT=3000 HOST='0.0.0.0' npm start`
    - app is listening on "http://0.0.0.0:3000/"
2. clone the electron app at https://github.com/deepak/electron-webview-todo and 
    - yarn/npm install
    - run app with `npm start`

I can start the React app but the Electron app does not boot

i am using Apple  OSX 10.10.5 aka Yosemite

The onlly weird part which happenned is that my hard disk became full
and OSX gave an alert saying "Your startup disk is full"

**Comment by paulcbetts** [comment]
Delete `$TMPDIR/.compileCache*`, your cache got corrupted because you ran out of disk space

**Comment by deepak** [comment]
thanks @paulcbetts 
restarting my laptop solved the issue

**Comment by deepak** [comment]
@paulcbetts what would be the equivalent command on windows ?

**Comment by paulcbetts** [comment]
@deepak 

```sh
rmdir /S %TEMP%/.compileCache*
```

**Comment by magne4000** [comment]
With version `1.7.1` I had to `rm -fr $TMPDIR/compileCache` (difference here, the missing `.`)
